### ISSUE TITLE
tests occasionally fail because no prometheus-tester units show up

### ISSUE THREAD

**Issue by sed-i** [canonical/prometheus-k8s-operator#193]
From the logs:
```
INFO     juju.model:model.py:2679 Waiting for model:
  prometheus-tester (not enough units yet - 0/1)
# ...
INFO     juju.model:model.py:2679 Waiting for model:
  prometheus-tester (not enough units yet - 0/1)
FAILED

____________ test_prometheus_scrape_relation_with_prometheus_tester ____________
Traceback (most recent call last):
  File "/home/runner/work/prometheus-k8s-operator/prometheus-k8s-operator/tests/integration/test_charm.py", line 81, in test_prometheus_scrape_relation_with_prometheus_tester
    await ops_test.model.wait_for_idle(apps=[tester_app_name], status="active")
  File "/home/runner/work/prometheus-k8s-operator/prometheus-k8s-operator/.tox/integration/lib/python3.8/site-packages/juju/model.py", line 2677, in wait_for_idle
    raise jasyncio.TimeoutError("Timed out waiting for model:\n" + busy)
asyncio.exceptions.TimeoutError: Timed out waiting for model:
prometheus-tester (not enough units yet - 0/1)
```

For example a rerun of the following passed:
https://github.com/canonical/prometheus-k8s-operator/runs/4710553937?check_suite_focus=true#step:4:303

**Comment by sed-i** [comment]
Possible solution:
```diff
    await ops_test.model.applications[app_name].remove()
+   await ops_test.model.block_until(lambda: app_name not in ops_test.model.applications)
    await ops_test.model.reset()
```
