### ISSUE TITLE
Error in alertmanager-relation-changed deploying in AWS

### ISSUE THREAD

**Issue by erik78se** [canonical/prometheus-k8s-operator#222]
I'm deploying charmcraft-prometheus to AWS.

Charm version  in charmhub.io:
Stable: 2 

This is probably for the VM charm, but the link points to this repo.

unit-prometheus-1: 10:22:33 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook
unit-prometheus-1: 10:22:34 ERROR unit.prometheus/1.juju-log alertmanager:4: Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 352, in <module>
    main(PrometheusCharm)
  File "/var/lib/juju/agents/unit-prometheus-1/charm/venv/ops/main.py", line 402, in main
    _emit_charm_event(charm, dispatcher.event_name)
  File "/var/lib/juju/agents/unit-prometheus-1/charm/venv/ops/main.py", line 140, in _emit_charm_event
    event_to_emit.emit(*args, **kwargs)
  File "/var/lib/juju/agents/unit-prometheus-1/charm/venv/ops/framework.py", line 278, in emit
    framework._emit(event)
  File "/var/lib/juju/agents/unit-prometheus-1/charm/venv/ops/framework.py", line 722, in _emit
    self._reemit(event_path)
  File "/var/lib/juju/agents/unit-prometheus-1/charm/venv/ops/framework.py", line 767, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 62, in _on_alertmanager_changed
    addrs = json.loads(event.relation.data[event.app].get('addrs', '[]'))
  File "/var/lib/juju/agents/unit-prometheus-1/charm/venv/ops/model.py", line 699, in __getitem__
    return self._data[key]
KeyError: <ops.model.Application alertmanager>
unit-prometheus-1: 10:22:34 ERROR juju.worker.uniter.operation hook "alertmanager-relation-changed" (via hook dispatching script: dispatch) failed: exit status 1
unit-prometheus-1: 10:22:34 INFO juju.worker.uniter awaiting error resolution for "relation-changed" hook

![image](https://user-images.githubusercontent.com/850603/152128088-66530b18-2d57-4c72-8a8d-b6dc36639c6e.png)

**Comment by simskij** [comment]
Hi,

Unfortunately the same applies here. `charmcraft-prometheus` is not the charm built from this repository (which is https://charmhub.io/prometheus-k8s).
Sorry again for the confusion.

Best,
Simme
