### ISSUE TITLE
hook failed: "update-status"

### ISSUE THREAD

**Issue by dstathis** [canonical/prometheus-k8s-operator#420]
### Bug Description

After deploying Prometheus, the update-status hook fails. Looks like it might be an ops issue. I can't reproduce this so it's probably some kind of race condition.

### To Reproduce

juju deploy prometheus-k8s prom --channel edge

### Environment

Prometheus revision: 93

$ snap list
Name        Version      Rev    Tracking       Publisher   Notes
...
juju        2.9.37       21315  latest/stable  canonical✓  classic
juju-wait   2.8.4~2.8.4  96     latest/stable  stub        classic
microk8s    v1.26.0      4390   1.26/stable    canonical✓  classic

### Relevant log output

```shell
unit-prom-0: 07:49:05 ERROR unit.prom/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
  File "./src/charm.py", line 777, in <module>
    main(PrometheusCharm)
  File "/var/lib/juju/agents/unit-prom-0/charm/venv/ops/main.py", line 436, in main
    framework.reemit()
  File "/var/lib/juju/agents/unit-prom-0/charm/venv/ops/framework.py", line 866, in reemit
    self._reemit()
  File "/var/lib/juju/agents/unit-prom-0/charm/venv/ops/framework.py", line 931, in _reemit
    custom_handler(event)
  File "./src/charm.py", line 465, in _update_status
    if self.unit.status != ActiveStatus():
  File "/var/lib/juju/agents/unit-prom-0/charm/venv/ops/model.py", line 443, in status
    self._status = StatusBase.from_name(s['status'], s['message'])
  File "/var/lib/juju/agents/unit-prom-0/charm/venv/ops/model.py", line 1131, in from_name
    return cls._statuses[name](message)
KeyError: 'error'
unit-prom-0: 07:49:05 ERROR juju.worker.uniter.operation hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by rbarry82** [comment]
This has [already been fixed](https://github.com/canonical/operator/issues/874), and there's a 2.0.0rc2 candidate up on PyPi. Probably nothing we need to do here but wait.
