### ISSUE TITLE
Charm reports permission denied when setting relation data

### ISSUE THREAD

**Issue by kian99** [canonical/prometheus-k8s-operator#582]
### Bug Description

The prometheus-k8s charm was working fine until suddenly it went into an error state with message "hook failed: update-status". The charm logs are reporting a permission error when reading/writing relation data.

### To Reproduce

Unsure

### Environment

Juju v3.1.6
Charmed Kubernetes
Prometheus-k8s latest/stable  rev. 159

### Relevant log output

```shell
2024-03-25T07:01:17.842Z [container-agent] 2024-03-25 07:01:17 DEBUG juju-log receive_response_body.started request=<Request [b'GET']>
2024-03-25T07:01:17.847Z [container-agent] 2024-03-25 07:01:17 DEBUG juju-log receive_response_body.complete
2024-03-25T07:01:17.853Z [container-agent] 2024-03-25 07:01:17 DEBUG juju-log response_closed.started
2024-03-25T07:01:17.857Z [container-agent] 2024-03-25 07:01:17 DEBUG juju-log response_closed.complete
2024-03-25T07:01:17.885Z [container-agent] 2024-03-25 07:01:17 DEBUG juju-log Setting Grafana data sources: {'model': 'stg-cos-lite-comsys', 'model_uuid': 'b8a87977-61c8-4ac7-8a66-699d8c6e4f7f', 'application': 'prometheus', 'type': 'prometheus', 'extra_fields': {'timeInterval': '1m'}}
2024-03-25T07:01:17.995Z [container-agent] 2024-03-25 07:01:17 ERROR juju-log Uncaught exception while in charm code:
2024-03-25T07:01:17.995Z [container-agent] Traceback (most recent call last):
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 2955, in _run
2024-03-25T07:01:17.995Z [container-agent]     result = subprocess.run(args, **kwargs)  # type: ignore
2024-03-25T07:01:17.995Z [container-agent]   File "/usr/lib/python3.8/subprocess.py", line 516, in run
2024-03-25T07:01:17.995Z [container-agent]     raise CalledProcessError(retcode, process.args,
2024-03-25T07:01:17.995Z [container-agent] subprocess.CalledProcessError: Command '('/var/lib/juju/tools/unit-prometheus-0/relation-set', '-r', '48', '--file', '-')' returned non-zero exit status 1.
2024-03-25T07:01:17.995Z [container-agent] 
2024-03-25T07:01:17.995Z [container-agent] The above exception was the direct cause of the following exception:
2024-03-25T07:01:17.995Z [container-agent] 
2024-03-25T07:01:17.995Z [container-agent] Traceback (most recent call last):
2024-03-25T07:01:17.995Z [container-agent]   File "./src/charm.py", line 1005, in <module>
2024-03-25T07:01:17.995Z [container-agent]     main(PrometheusCharm)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/main.py", line 436, in main
2024-03-25T07:01:17.995Z [container-agent]     _emit_charm_event(charm, dispatcher.event_name)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/main.py", line 144, in _emit_charm_event
2024-03-25T07:01:17.995Z [container-agent]     event_to_emit.emit(*args, **kwargs)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/framework.py", line 351, in emit
2024-03-25T07:01:17.995Z [container-agent]     framework._emit(event)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/framework.py", line 853, in _emit
2024-03-25T07:01:17.995Z [container-agent]     self._reemit(event_path)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/framework.py", line 942, in _reemit
2024-03-25T07:01:17.995Z [container-agent]     custom_handler(event)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/lib/charms/tempo_k8s/v0/charm_tracing.py", line 455, in wrapped_function
2024-03-25T07:01:17.995Z [container-agent]     return callable(*args, **kwargs)  # type: ignore
2024-03-25T07:01:17.995Z [container-agent]   File "./src/charm.py", line 605, in _update_status
2024-03-25T07:01:17.995Z [container-agent]     self._configure(event)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/lib/charms/tempo_k8s/v0/charm_tracing.py", line 455, in wrapped_function
2024-03-25T07:01:17.995Z [container-agent]     return callable(*args, **kwargs)  # type: ignore
2024-03-25T07:01:17.995Z [container-agent]   File "./src/charm.py", line 496, in _configure
2024-03-25T07:01:17.995Z [container-agent]     self.remote_write_provider.update_endpoint()
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/lib/charms/prometheus_k8s/v1/prometheus_remote_write.py", line 674, in update_endpoint
2024-03-25T07:01:17.995Z [container-agent]     self._set_endpoint_on_relation(relation)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/lib/charms/prometheus_k8s/v1/prometheus_remote_write.py", line 682, in _set_endpoint_on_relation
2024-03-25T07:01:17.995Z [container-agent]     relation.data[self._charm.unit]["remote_write"] = json.dumps(
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 1666, in __setitem__
2024-03-25T07:01:17.995Z [container-agent]     self._commit(key, value)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 1670, in _commit
2024-03-25T07:01:17.995Z [container-agent]     self._backend.update_relation_data(self.relation.id, self._entity, key, value)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 3291, in update_relation_data
2024-03-25T07:01:17.995Z [container-agent]     self.relation_set(relation_id, key, value, isinstance(_entity, Application))
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 3060, in relation_set
2024-03-25T07:01:17.995Z [container-agent]     self._run(*args, input_stream=content)
2024-03-25T07:01:17.995Z [container-agent]   File "/var/lib/juju/agents/unit-prometheus-0/charm/venv/ops/model.py", line 2957, in _run
2024-03-25T07:01:17.995Z [container-agent]     raise ModelError(e.stderr) from e
2024-03-25T07:01:17.995Z [container-agent] ops.model.ModelError: ERROR cannot read relation settings: permission denied
2024-03-25T07:01:17.995Z [container-agent] 
2024-03-25T07:01:18.270Z [container-agent] 2024-03-25 07:01:18 ERROR juju.worker.uniter.operation runhook.go:180 hook "update-status" (via hook dispatching script: dispatch) failed: exit status 1
```

**Comment by kian99** [comment]
Most likely a Juju anomaly, I can't remember what I did to fix it at the time but it hasn't happened since so I'll close the issue.
